### ISSUE TITLE
Error creating S3 bucket

### ISSUE THREAD

**Issue by fhajji** [servian/hashiqube#1]
Hello,
giving hashiqube a spin, I get the following error:

    hashiqube0.service.consul: Error: Error creating S3 bucket: RequestError: send request failed
    hashiqube0.service.consul: caused by: Put http://localhost:4572/localstack-s3-bucket: dial tcp 127.0.0.1:4572: connect: connection refused
    hashiqube0.service.consul: 
    hashiqube0.service.consul:   on main.tf line 37, in resource "aws_s3_bucket" "localstack-s3-bucket":
    hashiqube0.service.consul:   37: resource "aws_s3_bucket" "localstack-s3-bucket" {
    hashiqube0.service.consul: 
    hashiqube0.service.consul: 
    hashiqube0.service.consul: ++++ awslocal s3 ls..
    hashiqube0.service.consul: 
    hashiqube0.service.consul: Could not connect to the endpoint URL: "http://localhost:4572/"
The VM is running though:
vagrant@hashiqube0:~$ awslocal s3 ls

Could not connect to the endpoint URL: "http://localhost:4572/"

**Comment by star3am** [comment]
Hi @fhajji thank you for submitting the 1st issue! That is great of you! :)

I see the error during provision 
```
hashiqube0.service.consul: docker: Error response from daemon: driver failed programming external connectivity on endpoint localstack_main (1462e1122e72a4a5683d58a109e431f378981ce78fa4444234d3b2be04bc84b1): Bind for 0.0.0.0:8080 failed: port is already allocated.
    hashiqube0.service.consul: Starting local dev environment. CTRL-C to quit.
    hashiqube0.service.consul: docker run -it -d -e TEST_AWS_ACCOUNT_ID="000000000000" -e LOCALSTACK_HOSTNAME="localhost" -e DEFAULT_REGION="us-east-1" -p 443:443 -p 4566:4566 --rm --privileged --name localstack_main -p 8080:8080 -p 8081:8081  -p 4567-4617:4567-4617 -p 8080:8080  -v "/tmp/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/tmp/localstack" "localstack/localstack"
```

in localstack/localstack.sh I issue the start command 
`sudo -E ENTRYPOINT=-d localstack start --docker` I have disabled that and replaced it with

```
sudo docker run -it -d -e DEFAULT_REGION="us-east-1" -e TEST_AWS_ACCOUNT_ID="000000000000" -e LOCALSTACK_HOSTNAME="localhost" -p 7443:443 -p 4566:4566 --rm --privileged --name localstack_main -p 8080:8080 -p 8081:8081  -p 4567-4617:4567-4617 -v "/tmp/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/tmp/localstack" "localstack/localstack"
```

You can pull master and do `vagrant reload --provision`

Thanks again for raising the issue, have a wonderful easter weekend, 

Riaan

**Comment by fhajji** [comment]
Good catch! It really works now. Time to start exploring.

Thank you for this great project.

Happy Easter to you too.

-Farid.

**Comment by star3am** [comment]
That's great, thanks for confirming the fix :) 

My pleasure! It helped me and I hope it will help you too! Good luck with your future. 

Riaan
