### ISSUE TITLE
Error creating S3 bucket

### ISSUE THREAD

**Issue by abdelhaleemahmed** [servian/hashiqube#10]
I got the following error trying to build the VM, I tried multiple times.  

  hashiqube0.service.consul: aws_s3_bucket.localstack-s3-bucket: Creating...
    hashiqube0.service.consul: aws_s3_bucket.localstack-s3-bucket: Still creating... [10s elapsed]
    hashiqube0.service.consul: aws_s3_bucket.localstack-s3-bucket: Still creating... [20s elapsed]
    hashiqube0.service.consul: ╷
    hashiqube0.service.consul: │ Error: Error creating S3 bucket: RequestError: send request failed
    hashiqube0.service.consul: │ caused by: Put "http://localhost:4572/localstack-s3-bucket": dial tcp 127.0.0.1:4572: connect: connection refused
    hashiqube0.service.consul: │
    hashiqube0.service.consul: │   with aws_s3_bucket.localstack-s3-bucket,
    hashiqube0.service.consul: │   on main.tf line 37, in resource "aws_s3_bucket" "localstack-s3-bucket":
    hashiqube0.service.consul: │   37: resource "aws_s3_bucket" "localstack-s3-bucket" {
    hashiqube0.service.consul: │
    hashiqube0.service.consul: ╵
    hashiqube0.service.consul: ++++ awslocal s3 ls..
    hashiqube0.service.consul:
    hashiqube0.service.consul: Could not connect to the endpoint URL: "http://localhost:4566/"
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by star3am** [comment]
Hallo there @abdelhaleemahmed thank you for reporting the issue! We appreciate it! 

We have updated localstack, the ports for localstack has changed, please clone the latest master branch and see if this works for you, in addition we also added some more examples of localstack with more resources to help you learn :) 

Thanks for using HashiQube! <3
