### ISSUE TITLE
Vagrant up fails on Apple Silicon Mac

### ISSUE THREAD

**Issue by krital** [servian/hashiqube#13]
Hi there, 

I have been trying to test provisioning to docker on an apple silicon Mac and I am getting an error. The command I used is: 

`vagrant up --provision --provider docker`

and the error I get is:

`   hashiqube0.service.consul: ==> docker: Executing Ansible: ansible-playbook -e packer_build_name="docker" -e packer_builder_type=docker --extra-vars ansible_host=default ansible_connection=docker -e ansible_ssh_private_key_file=/tmp/ansible-key335928757 -i /tmp/packer-provisioner-ansible2601601172 /vagrant/hashicorp/packer/linux/ubuntu/playbook.yml
    hashiqube0.service.consul:     docker:
    hashiqube0.service.consul:     docker: PLAY [A demo to run ansible in a docker container] *****************************
    hashiqube0.service.consul:     docker:
    hashiqube0.service.consul:     docker: TASK [Gathering Facts] *********************************************************
    hashiqube0.service.consul:     docker: ok: [default]
    hashiqube0.service.consul:     docker: [WARNING]: Distribution Ubuntu 16.04 on host default should use
    hashiqube0.service.consul:     docker: /usr/bin/python3, but is using /usr/bin/python2.7, since the discovered
    hashiqube0.service.consul:     docker: platform python interpreter was not present. See
    hashiqube0.service.consul:     docker: https://docs.ansible.com/ansible-
    hashiqube0.service.consul:     docker: core/2.13/reference_appendices/interpreter_discovery.html for more information.
    hashiqube0.service.consul:     docker:
    hashiqube0.service.consul:     docker: TASK [Add a file to root's home dir] *******************************************
    hashiqube0.service.consul:     docker: changed: [default]
    hashiqube0.service.consul:     docker:
    hashiqube0.service.consul:     docker: TASK [Return all kv v2 secrets from a path] ************************************
    hashiqube0.service.consul:     docker: [DEPRECATION WARNING]: The default value for 'token_validate' will change from
    hashiqube0.service.consul:     docker: True to False. This feature will be removed from community.hashi_vault in
    hashiqube0.service.consul:     docker: version 4.0.0. Deprecation warnings can be disabled by setting
    hashiqube0.service.consul:     docker: deprecation_warnings=False in ansible.cfg.
    hashiqube0.service.consul:     docker: fatal: [default]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'hashi_vault'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Invalid Vault Token Specified.. Invalid Vault Token Specified."}
    hashiqube0.service.consul:     docker:
    hashiqube0.service.consul:     docker: PLAY RECAP *********************************************************************
    hashiqube0.service.consul:     docker: default                    : ok=2    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
    hashiqube0.service.consul:     docker:
    hashiqube0.service.consul: ==> docker: Provisioning step had errors: Running the cleanup provisioner, if present...
    hashiqube0.service.consul: ==> docker: Killing the container: 82cdc79e4953480826d199aa4649ec08888c6f4133dfe698d31bc6fb33ef1870
    hashiqube0.service.consul: Build 'docker' errored after 36 seconds 905 milliseconds: Error executing Ansible: Non-zero exit status: exit status 2
    hashiqube0.service.consul:
    hashiqube0.service.consul: ==> Wait completed after 36 seconds 906 milliseconds
    hashiqube0.service.consul:
    hashiqube0.service.consul: ==> Some builds didn't complete successfully and had errors:
    hashiqube0.service.consul: --> docker: Error executing Ansible: Non-zero exit status: exit status 2
    hashiqube0.service.consul:
    hashiqube0.service.consul: ==> Builds finished but no artifacts were created.`

Any ideas how I can work around it?

**Comment by star3am** [comment]
@krital thank you for raising this bug. I have started getting all the provisioners to support arm64 - but packer was one that I have not gotten too, additionally, I did not ensure that vault is running. I have now pushed a fix and you can give latest master a try. I have tested this on my mac m1 and it's working now. 

due to slow internet connections, changes on upstream dependencies, such as localstack etc. all provisioners might not work all the time. 

Docker is the default provider so you should be able to leave this part out completely "--provider docker"

for that reason, you can rerun individual provisioners and I usually do this: 

```
vagrant up --provision-with basetools
vagrant up --provision-with docker
vagrant up --provision-with vault
vagrant up --provision-with nomad
vagrant up --provision-with minikube
vagrant up --provision-with packer
vagrant up --provision-with docsify
```

Happy learning and stay curious!

Riaan
