### ISSUE TITLE
Error while executing `VBoxManage

### ISSUE THREAD

**Issue by i-walker** [servian/hashiqube#2]
Hi, thank you for setting this project up. 
I tried following the instructions, but I keep on getting this error:
running `vagrant up --provision`
```
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg *)" at line 94 of file VBoxManageHostonly.cpp
```
Any help is welcomed :)

**Comment by i-walker** [comment]
I found the issue now. There were some access rights that had to be over written. :)

**Comment by star3am** [comment]
I just wanted to thank you @i-walker for opening a ticket and after realizing the fix closing it again, that is most awesome of you! You can tell a lot about a person from the way they manage github issues <3 shout if you need help anywhere :)
