### ISSUE TITLE
ModuleNotFoundError: No module named 'pytz'

### ISSUE THREAD

**Issue by iamashks** [servian/hashiqube#27]
When installing dbt with all default options using the command vagrant up --provision-with basetools,docsify,docker,postgresql,dbt, I received the error "hashiqube0.service.consul: ModuleNotFoundError: No module named 'pytz'".

I have found the fix and raised a PR here: https://github.com/servian/hashiqube/pull/26

**Comment by star3am** [comment]
Thank you so much for your PR, I have merged it!
