### ISSUE TITLE
Setup your great HashiQube to an other IP space like 192.x.x.

### ISSUE THREAD

**Issue by Urs-Bruelhart** [servian/hashiqube#3]
I started to setup your solution and run into the issue that i have an other local IP range.

Meanwhile i saw that your IP range 10.x.x.x is hardcoded in some config files. I am thinking about to add a general pre-install .sh with variabels and requires in the config files.

What do you think about this solution in general?

Thank you in advance for some words about it to a advanced beginner ;-).

With best regards
Urs

**Comment by Urs-Bruelhart** [comment]
Perfect.

It was my own issue ;-).

**Comment by Urs-Bruelhart** [comment]
Wrong VirtualBox network. With the right one all is perfect.

**Comment by star3am** [comment]
Great work on getting that working, you can change the IP Address here :) https://github.com/servian/hashiqube/blob/master/Vagrantfile#L26
