### ISSUE TITLE
fabio dead

### ISSUE THREAD

**Issue by boriphuth** [servian/hashiqube#4]
Hi there,

Please find in below image.
![image](https://user-images.githubusercontent.com/3132377/88255394-7f619c00-cce2-11ea-9d2e-5c3859e4d4c1.png)

**Description**
Failed to create container configuration for image "fabiolb/fabio" ("sha256:3d652f62fddf53dba25b86b7d2ca7d472abb90dc0f195c0a95758ef540467b42"): volumes are not enabled; cannot mount host paths: "/vagrant/hashicorp/nomad/jobs:/etc/fabio"

**For my workaround** 
On the fabio.nomad I'm comment the volumes.
![image](https://user-images.githubusercontent.com/3132377/88255536-d0719000-cce2-11ea-895b-dbc9a60870cf.png)

**Comment by star3am** [comment]
Good morning @boriphuth thank you for opening an issue. By the looks of it your vagrant folder is not mounted which leads me to believe your guest additions are not working. Can you see if you can access /vagrant inside the VM, this should mount your hashiqube repository folder inside the virtual machine. From there fabio can access the fabio configuration file. 

Let me know how that goes. 

Riaan

**Comment by star3am** [comment]
Hi there @boriphuth - I had a closer look into this with the new version of Nomad and it seems that I had to enable Docker Volume mounts in Nomad client, I have pushed this commit to fix the failing mount. 

https://github.com/servian/hashiqube/commit/540abb5ede6ee2a9754e7374e3073dc4e70060df

Could you be so kind as to pull master and test on your side, 

Thank you so much, 

Riaan

**Comment by star3am** [comment]
Closing this issue, @boriphuth if you still have problems please reopen this issue :)
