### ISSUE TITLE
Updating nomad agent to point to a docker daemon running elsewhere (outside vagrant)

### ISSUE THREAD

**Issue by gc-ss** [servian/hashiqube#8]
First, I REALLY appreciate this project.

Now, I am unsure whether this question belongs here or not but in case you're curious here are the details:

https://discuss.hashicorp.com/t/pointing-nomad-to-a-remote-docker-daemon-over-tcp/24997

So, would there be any value or interest in having this project have the ability for updating nomad to point to a docker daemon running elsewhere outside vagrant?

**Comment by star3am** [comment]
Thank you so much for the beautiful compliment <3 I am so happy that you find it useful! 

About your issue, you could update hashicorp/nomad.sh with the external address and port of the docker daemon and it should work but this seems out of scope for the projects purpose, we tried to keep it simple and without much effort, nevertheless, thank you so much for opening an issue, we value your feedback.

Riaan
